version: '3.3'

services:
  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=my_bd
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123456
    ports:
      - '5432:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
